name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What should we build?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is it valuable?
    validations:
      required: false
